# Generated by Django 5.2 on 2025-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('departement_id', models.AutoField(primary_key=True, serialize=False)),
                ('departement_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('departement', models.CharField(max_length=50)),
                ('job_level', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=50)),
                ('employment_status', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
