# Generated by Django 5.2 on 2025-04-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departement_old',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='day_payment',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.departement'),
        ),
    ]
