# Generated by Django 5.2 on 2025-04-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_employee_departement_old_alter_employee_day_payment_and_more'),
        ('EmployeeApp', '0004_auto_20250407_0150'),
    ]

    operations = [
    ]
