# Generated by Django 5.2 on 2025-04-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_merge_20250407_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='departement_id',
        ),
        migrations.AddField(
            model_name='departement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='departement_name',
            field=models.CharField(max_length=100),
        ),
    ]
