# Generated by Django 5.2 on 2025-04-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_remove_departement_departement_id_departement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departement_old',
        ),
    ]
