# Generated by Django 5.2 on 2025-05-01 03:53

import EmployeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_remove_employee_departement_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeApp.models.certification_upload_path),
        ),
    ]
